// posts
export const FETCH_POSTS__REQUEST = "FETCH_POSTS__REQUEST";
export const FETCH_POSTS_SUCCESS_REQUEST = "FETCH_POSTS_SUCCESS_REQUEST";
export const FETCH_POSTS_FAILURE_REQUEST = "FETCH_POSTS_FAILURE_REQUEST";

// comments
export const FETCH_COMMENTS__REQUEST = "FETCH_COMMENTS__REQUEST";
export const FETCH_COMMENTS_SUCCESS_REQUEST = "FETCH_COMMENTS_SUCCESS_REQUEST";
export const FETCH_COMMENTS_FAILURE_REQUEST = "FETCH_COMMENTS_FAILURE_REQUEST";

// photos
export const FETCH_PHOTOS__REQUEST = "FETCH_PHOTOS__REQUEST";
export const FETCH_PHOTOS_SUCCESS_REQUEST = "FETCH_PHOTOS_SUCCESS_REQUEST";
export const FETCH_PHOTOS_FAILURE_REQUEST = "FETCH_PHOTOS_FAILURE_REQUEST";
