import Head from "next/head";
import React, { ReactElement } from "react";
import Footer from "./footer/Index";
import Header from "./header/Index";
interface LayoutProps {
  children: ReactElement | ReactElement[];
  title: string;
}
const Layout = ({ children, title }: LayoutProps): ReactElement => {
  return (
    <React.Fragment>
      <Head>
        <title>SOFTIC- {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="fonts/stylesheet.css"></link> */}
        {/* <link rel="stylesheet" href="/fonts/stylesheet.css"></link> */}
      </Head>
      <Header />
      <main className="main" id="main">
        {children}
      </main>
      <Footer />
    </React.Fragment>
  );
};

export default Layout;
